### ISSUE TITLE
TimecodeFPS: "start" parameter

### ISSUE THREAD

**Issue by Reel-Deal** [nattthebear/avisynthjunk#1]
Hi Natt,

First of all thank you for the timecodefps plugin. I recently found out about it and started using it over the other available vfr to cfr plugins available for AviSynth.

I wanted to ask, what is the _start_ parameter used for? It is not documented.

Also, any possibly of getting an x64 build to use with [AviSynth+](https://github.com/pinterf/AviSynthPlus)?

**Comment by nattthebear** [comment]
`start` is boolean.  If set to true, the 0th timecode in the file is assumed to be at the 0 time.  If set to false, the exact number t=0 is assumed to be the 0 time.

So for example, if the timecode for the 0th frame is at 6 seconds in, then if start = false, 6 seconds of pure black frames will be introduced into the output.  When start = true, things will just start with that 0th frame being the first frame in the output and the 6 seconds will be omitted.

> Also, any possibly of getting an x64 build to use with AviSynth+?

@vadosnaprimer did you ever look into this?

**Comment by vadosnaprimer** [comment]
I was unable to build some of those things and stopped caring.

**Comment by nattthebear** [comment]
x64 build probably isn't a possibility then.

**Comment by Reel-Deal** [comment]
Natt,

Thanks you for taking time to explain the `start` parameter. I have encountered some files (mainly flvs) with many leading 0s.  

I'll see if maybe someone over at Doom9 has any interest in trying to compile an x64 build.
